### ISSUE TITLE
cannot read property 'registerApp' of undefined

### ISSUE THREAD

**Issue by gp5251** [weflex/react-native-wechat#28] opened 2016-02-01 06:43 UTC
hi, 

when I add this line
    import WeChat from 'react-native-wechat';
in my script, I got this error 

![image](https://cloud.githubusercontent.com/assets/995572/12710476/05661410-c8f2-11e5-9d2a-ad928787917a.png)

, what is the matter ? how to resolve it ? 3q.

**Comment by anderson916** [comment] 2016-02-01 06:58
```
import * as WeChat from 'react-native-wechat'
```

**Comment by gp5251** [comment] 2016-02-01 07:02
no, still not work

**Comment by yorkie** [comment] 2016-02-01 08:11
Could you simply use the following way to require:

```
const wechat = require('react-native-wechat');
wechat.registerApp();
```

It's working on my app

**Comment by gp5251** [comment] 2016-02-01 08:18
now i got this...

![image](https://cloud.githubusercontent.com/assets/995572/12711972/46fccba0-c8ff-11e5-889c-a34f35923bd5.png)

**Comment by gp5251** [comment] 2016-02-01 08:25
but i got this...

![image](https://cloud.githubusercontent.com/assets/995572/12712057/4d54d2a8-c900-11e5-9dd6-84faf2d72536.png)

**Comment by gp5251** [comment] 2016-02-01 09:05
when i tried to log WeChat but got undefined , may be that is the problem, but why? i had added the RCTWeChat library and used the automatic link method(rnpm) introduced by fb.
![image](https://cloud.githubusercontent.com/assets/995572/12712739/760ab8b6-c905-11e5-93ca-d49fc5cb65d5.png)

**Comment by yorkie** [comment] 2016-02-01 10:03
Could you manually link in XCode, i have not yet tried with `rnpm`.

**Comment by letmeknowhow** [comment] 2016-02-12 04:25
I link it in XCode manually always, it works in v1.2.5, but only could use code 
`const WeChat = require("react-native-wechat");`
Today, I update v1.3.0, I got the same issue as gp5251, "WeChat" is undefined in index.js
`const {WeChat = NativeModules;}`

**Comment by yorkie** [comment] 2016-02-12 07:34
Could you run Example project correctly?

**Comment by letmeknowhow** [comment] 2016-02-12 12:09
no, but I don't think Example could help, I found the version of RN is 0.14, Does it need to 0.17 and above?
`"dependencies": {
    "es6-promisify": "^3.0.0",
    "react-native": "^0.14.2",
    "events": "1.0.2"
  }`

**Comment by letmeknowhow** [comment] 2016-02-12 13:53
I clean the project and re-link "react-native-wechat@1.3.0", then build failed because below line in "RCTWeChat.h":
#import "RCTBridgeModule.h"

**Comment by yorkie** [comment] 2016-02-12 14:25
Could you post your `{project}.xcodeproj/project.pbxproj` here so that I can see if your config is correct?

**Comment by letmeknowhow** [comment] 2016-02-12 14:41
I found the issue is Header Search Paths.
I change them to "$(SRCROOT)/../../react-native/React", then it build successfully, and I does not get "WeChat is undefined" issue.
The url you committed with "Example" word, please modify it. then notify me please, thx!

**Comment by lionrock** [comment] 2016-05-06 07:20
I've got the same problem.

and here is the log from xCode:

> 2016-05-06 15:19:47.997 [warn][tid:com.facebook.react.JavaScript] Warning: ReactNative.Component is deprecated. Use React.Component from the "react" package instead.
2016-05-06 15:19:47.999 [error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 'WeChat.registerApp')
2016-05-06 15:19:48.000 [fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'WeChat.registerApp')
2016-05-06 15:19:48.015 [error][tid:com.facebook.react.JavaScript] Module AppRegistry is not a registered callable module.
2016-05-06 15:19:48.016 [fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: Module AppRegistry is not a registered callable module.

**Comment by yorkie** [comment] 2016-05-06 07:27
@lionrock Got fixed if apply https://github.com/weflex/react-native-wechat/issues/28#issuecomment-183355831?

**Comment by lionrock** [comment] 2016-05-06 07:29
I'm fixing the error now

**Comment by yorkie** [comment] 2016-05-06 07:33
Okay, ping me if you still have any error on this issue :-)

**Comment by lionrock** [comment] 2016-05-06 07:34
Does the function `wechat.registerApp();` need a appid param ?
The WechatSDK show that it need a param(appid) which type is NSString

```
RCT_EXPORT_METHOD(registerApp:(NSString *)appid
                  :(RCTResponseSenderBlock)callback)
{
    self.appId = appid;
    callback(@[[WXApi registerApp:appid] ? [NSNull null] : INVOKE_FAILED]);
}
```

**Comment by yorkie** [comment] 2016-05-06 07:34
Yes, the `appId` should be required, doesn't it? (correct me if I'm wrong).

**Comment by lionrock** [comment] 2016-05-06 07:42
@yorkie got it : )

**Comment by yorkie** [comment] 2016-06-14 02:50
Verified it and it should be working now, closing.

**Closed by yorkie** 2016-06-14 02:50 UTC

**Comment by chunecai** [comment] 2017-07-14 02:53
![image](https://user-images.githubusercontent.com/7912599/28196329-83137e12-6882-11e7-9a45-d13e1d475ac2.png)
我的使用命令引入了，出现了同样的问题，应该是没生效，我的解决办法是如下：
![image](https://user-images.githubusercontent.com/7912599/28196356-af00052c-6882-11e7-9e81-26d5de1e779a.png)
重新再xcode中引入一下就好了。
--有相同的可参考尝试

**Comment by aleafo** [comment] 2018-11-19 06:00
楼上正解，但是对于不熟悉xcode的用户来说，可能看不太明白。再补充一下：rnpm link之后仍然报错的话，就是链接库没有成功。改为手动链接：

点击主工程项目文件(存在.xcodeproj文件的那个)，点击TARGETS里的主文件，然后选择Build Phases选项卡。
在左侧项目导航目录中，找到刚刚添加的 Libraries->RCTWeChat.xcodeproj -> Products 文件夹中的libRCTWeChat.a库，拖动到右侧的Link Binary With Libraries中。
然后重新编译一下RN项目即可。

- "react-native": "^0.57.4",
- "react-native-wechat": "^1.9.10",

测试通过。

![ee](https://user-images.githubusercontent.com/4177909/48688827-becd1080-ec02-11e8-9dc5-d7a8102422f1.jpg)

**Comment by rahamin1** [comment] 2019-02-19 15:34
@lionrock  (or anybody else :)  

Regarding appId: it is the appId of WeChat that is installed on the smartphone from where I am sharing, right? How do you get it from the app that is using react-native-wechat?
